name: DMP 2024 Project Template
description: List a new project for Dedicated Mentoring Program (DMP) 2024 
title: "[DMP 2024]: "
labels: ["DMP 2024"]
body:
  - type: string
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      description: "Provide a brief description of the feature, including why it is needed and what it will accomplish."

  - type: string
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals & Mid-Point Milestone
      description: "List the goals of the feature. Please add the goals that must be achieved by Mid-point check-in i.e 1.5 months into the coding period."

  - type: string
    id: ticket-setup
    attributes:
      label: Setup/Installation 
      description: "List or link setup or installation guide (if any)"

  - type: string
    id: ticket-expected-outcome
    attributes:
      label: Expected Outcome
      description: "Describe in detail what the final product or result should look like and how it should behave."

  - type: string
    id: ticket-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List the acceptance criteria for this feature."

  - type: string
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: "List any technical details about the proposed implementation, including any specific technologies that will be used."

  - type: string
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      description: "Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what the final product should look like."

  - type: string
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: "Enter Product Name"
    validations:
      required: true

  - type: string
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: "Enter Organisation Name"
      placeholder: "a2i"
    validations:
      required: true

  - type: string
    id: ticket-governance-domain
    attributes:
      label: Domain
      description: "Enter the domain of the project"
      placeholder: "Service Delivery"
    validations:
      required: true

  - type: string
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      description: "Specify the technology skills needed for this ticket"
      placeholder: "Laravel"
    validations:
      required: true
